/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-03 at 07:24:39 UTC 
 * Modify at your own risk.
 */

package com.example.myloveletter.loveletterendpoint;

/**
 * Service definition for Loveletterendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link LoveletterendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Loveletterendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the loveletterendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myloveletter1314.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "loveletterendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Loveletterendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Loveletterendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getLoveLetter".
   *
   * This request holds the parameters needed by the the loveletterendpoint server.  After setting any
   * optional parameters, call the {@link GetLoveLetter#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetLoveLetter getLoveLetter(java.lang.Long id) throws java.io.IOException {
    GetLoveLetter result = new GetLoveLetter(id);
    initialize(result);
    return result;
  }

  public class GetLoveLetter extends LoveletterendpointRequest<com.example.myloveletter.loveletterendpoint.model.LoveLetter> {

    private static final String REST_PATH = "loveletter/{id}";

    /**
     * Create a request for the method "getLoveLetter".
     *
     * This request holds the parameters needed by the the loveletterendpoint server.  After setting
     * any optional parameters, call the {@link GetLoveLetter#execute()} method to invoke the remote
     * operation. <p> {@link GetLoveLetter#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetLoveLetter(java.lang.Long id) {
      super(Loveletterendpoint.this, "GET", REST_PATH, null, com.example.myloveletter.loveletterendpoint.model.LoveLetter.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetLoveLetter setAlt(java.lang.String alt) {
      return (GetLoveLetter) super.setAlt(alt);
    }

    @Override
    public GetLoveLetter setFields(java.lang.String fields) {
      return (GetLoveLetter) super.setFields(fields);
    }

    @Override
    public GetLoveLetter setKey(java.lang.String key) {
      return (GetLoveLetter) super.setKey(key);
    }

    @Override
    public GetLoveLetter setOauthToken(java.lang.String oauthToken) {
      return (GetLoveLetter) super.setOauthToken(oauthToken);
    }

    @Override
    public GetLoveLetter setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetLoveLetter) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetLoveLetter setQuotaUser(java.lang.String quotaUser) {
      return (GetLoveLetter) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetLoveLetter setUserIp(java.lang.String userIp) {
      return (GetLoveLetter) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetLoveLetter setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetLoveLetter set(String parameterName, Object value) {
      return (GetLoveLetter) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertLoveLetter".
   *
   * This request holds the parameters needed by the the loveletterendpoint server.  After setting any
   * optional parameters, call the {@link InsertLoveLetter#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.myloveletter.loveletterendpoint.model.LoveLetter}
   * @return the request
   */
  public InsertLoveLetter insertLoveLetter(com.example.myloveletter.loveletterendpoint.model.LoveLetter content) throws java.io.IOException {
    InsertLoveLetter result = new InsertLoveLetter(content);
    initialize(result);
    return result;
  }

  public class InsertLoveLetter extends LoveletterendpointRequest<com.example.myloveletter.loveletterendpoint.model.LoveLetter> {

    private static final String REST_PATH = "loveletter";

    /**
     * Create a request for the method "insertLoveLetter".
     *
     * This request holds the parameters needed by the the loveletterendpoint server.  After setting
     * any optional parameters, call the {@link InsertLoveLetter#execute()} method to invoke the
     * remote operation. <p> {@link InsertLoveLetter#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.example.myloveletter.loveletterendpoint.model.LoveLetter}
     * @since 1.13
     */
    protected InsertLoveLetter(com.example.myloveletter.loveletterendpoint.model.LoveLetter content) {
      super(Loveletterendpoint.this, "POST", REST_PATH, content, com.example.myloveletter.loveletterendpoint.model.LoveLetter.class);
    }

    @Override
    public InsertLoveLetter setAlt(java.lang.String alt) {
      return (InsertLoveLetter) super.setAlt(alt);
    }

    @Override
    public InsertLoveLetter setFields(java.lang.String fields) {
      return (InsertLoveLetter) super.setFields(fields);
    }

    @Override
    public InsertLoveLetter setKey(java.lang.String key) {
      return (InsertLoveLetter) super.setKey(key);
    }

    @Override
    public InsertLoveLetter setOauthToken(java.lang.String oauthToken) {
      return (InsertLoveLetter) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertLoveLetter setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertLoveLetter) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertLoveLetter setQuotaUser(java.lang.String quotaUser) {
      return (InsertLoveLetter) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertLoveLetter setUserIp(java.lang.String userIp) {
      return (InsertLoveLetter) super.setUserIp(userIp);
    }

    @Override
    public InsertLoveLetter set(String parameterName, Object value) {
      return (InsertLoveLetter) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listLoveLetter".
   *
   * This request holds the parameters needed by the the loveletterendpoint server.  After setting any
   * optional parameters, call the {@link ListLoveLetter#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListLoveLetter listLoveLetter() throws java.io.IOException {
    ListLoveLetter result = new ListLoveLetter();
    initialize(result);
    return result;
  }

  public class ListLoveLetter extends LoveletterendpointRequest<com.example.myloveletter.loveletterendpoint.model.CollectionResponseLoveLetter> {

    private static final String REST_PATH = "loveletter";

    /**
     * Create a request for the method "listLoveLetter".
     *
     * This request holds the parameters needed by the the loveletterendpoint server.  After setting
     * any optional parameters, call the {@link ListLoveLetter#execute()} method to invoke the remote
     * operation. <p> {@link ListLoveLetter#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListLoveLetter() {
      super(Loveletterendpoint.this, "GET", REST_PATH, null, com.example.myloveletter.loveletterendpoint.model.CollectionResponseLoveLetter.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListLoveLetter setAlt(java.lang.String alt) {
      return (ListLoveLetter) super.setAlt(alt);
    }

    @Override
    public ListLoveLetter setFields(java.lang.String fields) {
      return (ListLoveLetter) super.setFields(fields);
    }

    @Override
    public ListLoveLetter setKey(java.lang.String key) {
      return (ListLoveLetter) super.setKey(key);
    }

    @Override
    public ListLoveLetter setOauthToken(java.lang.String oauthToken) {
      return (ListLoveLetter) super.setOauthToken(oauthToken);
    }

    @Override
    public ListLoveLetter setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListLoveLetter) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListLoveLetter setQuotaUser(java.lang.String quotaUser) {
      return (ListLoveLetter) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListLoveLetter setUserIp(java.lang.String userIp) {
      return (ListLoveLetter) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListLoveLetter setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListLoveLetter setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListLoveLetter set(String parameterName, Object value) {
      return (ListLoveLetter) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeLoveLetter".
   *
   * This request holds the parameters needed by the the loveletterendpoint server.  After setting any
   * optional parameters, call the {@link RemoveLoveLetter#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveLoveLetter removeLoveLetter(java.lang.Long id) throws java.io.IOException {
    RemoveLoveLetter result = new RemoveLoveLetter(id);
    initialize(result);
    return result;
  }

  public class RemoveLoveLetter extends LoveletterendpointRequest<Void> {

    private static final String REST_PATH = "loveletter/{id}";

    /**
     * Create a request for the method "removeLoveLetter".
     *
     * This request holds the parameters needed by the the loveletterendpoint server.  After setting
     * any optional parameters, call the {@link RemoveLoveLetter#execute()} method to invoke the
     * remote operation. <p> {@link RemoveLoveLetter#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveLoveLetter(java.lang.Long id) {
      super(Loveletterendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveLoveLetter setAlt(java.lang.String alt) {
      return (RemoveLoveLetter) super.setAlt(alt);
    }

    @Override
    public RemoveLoveLetter setFields(java.lang.String fields) {
      return (RemoveLoveLetter) super.setFields(fields);
    }

    @Override
    public RemoveLoveLetter setKey(java.lang.String key) {
      return (RemoveLoveLetter) super.setKey(key);
    }

    @Override
    public RemoveLoveLetter setOauthToken(java.lang.String oauthToken) {
      return (RemoveLoveLetter) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveLoveLetter setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveLoveLetter) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveLoveLetter setQuotaUser(java.lang.String quotaUser) {
      return (RemoveLoveLetter) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveLoveLetter setUserIp(java.lang.String userIp) {
      return (RemoveLoveLetter) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveLoveLetter setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveLoveLetter set(String parameterName, Object value) {
      return (RemoveLoveLetter) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateLoveLetter".
   *
   * This request holds the parameters needed by the the loveletterendpoint server.  After setting any
   * optional parameters, call the {@link UpdateLoveLetter#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.myloveletter.loveletterendpoint.model.LoveLetter}
   * @return the request
   */
  public UpdateLoveLetter updateLoveLetter(com.example.myloveletter.loveletterendpoint.model.LoveLetter content) throws java.io.IOException {
    UpdateLoveLetter result = new UpdateLoveLetter(content);
    initialize(result);
    return result;
  }

  public class UpdateLoveLetter extends LoveletterendpointRequest<com.example.myloveletter.loveletterendpoint.model.LoveLetter> {

    private static final String REST_PATH = "loveletter";

    /**
     * Create a request for the method "updateLoveLetter".
     *
     * This request holds the parameters needed by the the loveletterendpoint server.  After setting
     * any optional parameters, call the {@link UpdateLoveLetter#execute()} method to invoke the
     * remote operation. <p> {@link UpdateLoveLetter#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.example.myloveletter.loveletterendpoint.model.LoveLetter}
     * @since 1.13
     */
    protected UpdateLoveLetter(com.example.myloveletter.loveletterendpoint.model.LoveLetter content) {
      super(Loveletterendpoint.this, "PUT", REST_PATH, content, com.example.myloveletter.loveletterendpoint.model.LoveLetter.class);
    }

    @Override
    public UpdateLoveLetter setAlt(java.lang.String alt) {
      return (UpdateLoveLetter) super.setAlt(alt);
    }

    @Override
    public UpdateLoveLetter setFields(java.lang.String fields) {
      return (UpdateLoveLetter) super.setFields(fields);
    }

    @Override
    public UpdateLoveLetter setKey(java.lang.String key) {
      return (UpdateLoveLetter) super.setKey(key);
    }

    @Override
    public UpdateLoveLetter setOauthToken(java.lang.String oauthToken) {
      return (UpdateLoveLetter) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateLoveLetter setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateLoveLetter) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateLoveLetter setQuotaUser(java.lang.String quotaUser) {
      return (UpdateLoveLetter) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateLoveLetter setUserIp(java.lang.String userIp) {
      return (UpdateLoveLetter) super.setUserIp(userIp);
    }

    @Override
    public UpdateLoveLetter set(String parameterName, Object value) {
      return (UpdateLoveLetter) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Loveletterendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Loveletterendpoint}. */
    @Override
    public Loveletterendpoint build() {
      return new Loveletterendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link LoveletterendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setLoveletterendpointRequestInitializer(
        LoveletterendpointRequestInitializer loveletterendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(loveletterendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
